on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check_create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - run: go run main.go --record

      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
  